Fix: fix ERR_REQUIRE_ESM error
The semantic-release packages are throwing the following error when used by
semantic-release-notes-preview.

(The message below was redacted to fit in the commit message.)
```
Error: Error [ERR_REQUIRE_ESM]: require() of ES Module @semantic-release/commit-analyzer/index.js
from dist/index.js not supported.
```

This is probably cause by the following issue.
https://github.com/semantic-release/semantic-release/issues/2133